### ISSUE TITLE
Version 4.2.0 of git cookbook conflicts with mysql cookbook LWRP

### ISSUE THREAD

**Issue by schwing** [rackspace-cookbooks/stack_commons#120]
```
Recipe: git::default
  * git_client[default] action install
 
    ================================================================================
    Error executing action `install` on resource 'git_client[default]'
    ================================================================================
 
    NoMethodError
    -------------
    undefined method `package_version' for Chef::Resource::AptPackage
 
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/mysql/libraries/resource_mysql_service.rb:59:in `parsed_package_version'
    /var/chef/cache/cookbooks/git/libraries/provider_git_client_package.rb:16:in `block (2 levels) in <class:Package>'
    /var/chef/cache/cookbooks/git/libraries/provider_git_client_package.rb:14:in `block in <class:Package>'
 
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/git/recipes/default.rb
 
     19: git_client 'default' do
     20:   action :install
     21: end
 
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/git/recipes/default.rb:19:in `from_file'
 
    git_client("default") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :git_client
      cookbook_name "git"
      recipe_name "default"
    end
```

This is caused by https://github.com/chef-cookbooks/mysql/blob/v5.6.1/libraries/resource_mysql_service.rb#L58-L60
and https://github.com/jssjr/git/blob/4733ad3f574680f900c44eddffb6081ab4ca7106/libraries/helpers.rb#L11-L13 conflicting, from the look of it. Conflicting version 4.2.0 of the git cookbook was released yesterday.

Including the git::default recipe seems overkill just to install the package at https://github.com/rackspace-cookbooks/platformstack/blob/master/recipes/ohai_plugins.rb#L12 and nothing else. This dependency should be removed and replaced with a simple package install, unless there's some pressing reason not to.

**Comment by schwing** [comment]
Wrong repo. Closing for https://github.com/rackspace-cookbooks/platformstack/issues/198
