### ISSUE TITLE
Convergence failure on CentOS

### ISSUE THREAD

**Issue by martinb3** [rackspace-cookbooks/stack_commons#85]
We are seeing some new convergence failures due to the issue described at https://github.com/poise/python/issues/100.

```
       Recipe: python::package
         * package[python] action install[2015-01-02T14:44:25+00:00] INFO: Processing package[python] action install (python::package line 41)
        (up to date)
         * package[python-devel] action install
       [2015-01-02T14:44:25+00:00] INFO: Processing package[python-devel] action install (python::package line 41)
       [2015-01-02T14:44:25+00:00] INFO: package[python-devel] installing python-devel-2.6.6-52.el6 from base repository
       
           - install version 2.6.6-52.el6 of package python-devel
       Recipe: python::pip
         * cookbook_file[/tmp/kitchen/cache/get-pip.py] action create[2015-01-02T14:44:27+00:00] INFO: Processing cookbook_file[/tmp/kitchen/cache/get-pip.py] action create (python::pip line 36)
        (skipped due to not_if)
         * execute[install-pip] action run[2015-01-02T14:44:27+00:00] INFO: Processing execute[install-pip] action run (python::pip line 42)
        (skipped due to not_if)
         * python_pip[setuptools] action upgrade
       [2015-01-02T14:44:27+00:00] INFO: Processing python_pip[setuptools] action upgrade (python::pip line 50)
       [2015-01-02T14:44:27+00:00] INFO: Upgrading python_pip[setuptools] version from uninstalled to latest
       
           - upgrade python_pip[setuptools] version from  to latest
       Recipe: python::virtualenv
         * python_pip[virtualenv] action upgrade[2015-01-02T14:44:29+00:00] INFO: Processing python_pip[virtualenv] action upgrade (python::virtualenv line 23)
       [2015-01-02T14:44:29+00:00] INFO: Upgrading python_pip[virtualenv] version from uninstalled to latest
       
           
           ================================================================================
           
       Error executing action `upgrade` on resource 'python_pip[virtualenv]'
           ================================================================================
           
       
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /usr/bin/pip install  --upgrade virtualenv ----
           STDOUT: Downloading/unpacking virtualenv
             Running setup.py egg_info for package virtualenv
               /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'entry_points'
                 warnings.warn(msg)
               /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'zip_safe'
                 warnings.warn(msg)
               /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'tests_require'
                 warnings.warn(msg)
               usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
                  or: -c --help [cmd1 cmd2 ...]
                  or: -c --help-commands
                  or: -c cmd --help
               
               error: invalid command 'egg_info'
               Complete output from command python setup.py egg_info:
               /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'entry_points'
           
             warnings.warn(msg)
           
           /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'zip_safe'
           
             warnings.warn(msg)
           
           /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'tests_require'
           
             warnings.warn(msg)
           
           usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
           
              or: -c --help [cmd1 cmd2 ...]
           
              or: -c --help-commands
       
           
       
              or: -c cmd --help
           
       
           
           
           error: invalid command 'egg_info'
           
           ----------------------------------------
           Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-root/virtualenv
           Storing complete log in /root/.pip/pip.log
           STDERR: 
           ---- End output of /usr/bin/pip install  --upgrade virtualenv ----
           Ran /usr/bin/pip install  --upgrade virtualenv returned 1
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/python/providers/pip.rb:158:in `pip_cmd'
           /tmp/kitchen/cache/cookbooks/python/providers/pip.rb:139:in `install_package'
           /tmp/kitchen/cache/cookbooks/python/providers/pip.rb:144:in `upgrade_package'
           /tmp/kitchen/cache/cookbooks/python/providers/pip.rb:60:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/python/providers/pip.rb:58:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/python/recipes/virtualenv.rb
           
            23: python_pip "virtualenv" do
            24:   action :upgrade
            25:   version node['python']['virtualenv_version']
            26: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/python/recipes/virtualenv.rb:23:in `from_file'
           
           
       python_pip("virtualenv") do
           
         action [:upgrade]
             retries 0
             retry_delay 2
             guard_interpreter :default
             cookbook_name "python"
             recipe_name "virtualenv"
             package_name "virtualenv"
             options " --upgrade"
             timeout 900
           end
```

**Comment by martinb3** [comment]
Fixed in #86.
